### ISSUE TITLE
创建战绩快照

### ISSUE THREAD

**Issue by Deycilcb** [dzxrly/BF2042State2.0#1]
可选 保存不同查询时间的战绩数据，方便作为对比。
或查询结果页可以添加一个当前结果查询时间。

**Comment by dzxrly** [comment]
非常抱歉，该功能暂时无法加入。原因如下：
1. 本应用没有真正意义上的配套后端，查看`/lib/api`可以看出全部请求接口均采用别人公开的。如果要加入类似战绩快照的功能则需要配套的后端，鉴于没有时间和用爱发电，很难完成构建；
2. 如果不考虑远程保存快照而是保存在本地，则需要考虑使用类似`sqlite`的数据库以替代目前应用使用的简单缓存机制，本着简单和轻量化考虑，个人并不想让应用体积和运行时内存占用膨胀。

综上所述，由于个人精力有限、用爱发电无法维护后端服务器，该功能暂时无法加入。希望能有其他有精力的大佬为您提供帮助。
