### ISSUE TITLE
输入框建议

### ISSUE THREAD

**Issue by Aonysen** [dzxrly/BF2042State2.0#2]
输入id时，输入法会遮住输入框，导致自己看不到输入的内容。

**Comment by Aonysen** [comment]
![Screenshot_2023-12-31-21-50-10-434_com eggtargaryen bf2042state](https://github.com/dzxrly/BF2042State2.0/assets/32866087/826e726d-0307-4265-bbc3-2a9bfbc62f1b)

**Comment by dzxrly** [comment]
已发布针对该问题的更新：[2.2.0.41版本更新](https://github.com/dzxrly/BF2042State2.0/releases/tag/2.2.0)
